export type TrustCard = { label: string; body: string; href?: string; linkLabel?: string };
export type TrustSection = { id: string; title: string; paragraphs?: string[]; cards?: TrustCard[] };
export type TrustPage = { title: string; description: string; standfirst: string; sections: TrustSection[] };

export const trustPages = {
  about: {
    title: "About OpenBrowse",
    description: "OpenBrowse is an open-source, self-hosted browser-agent runtime for teams that want to own the machine, data and operational choices behind their automation.",
    standfirst: "A browser agent you can inspect, operate and run on infrastructure you control.",
    sections: [
      { id: "about", title: "About OpenBrowse", paragraphs: ["OpenBrowse is an MIT-licensed, self-hosted alternative to Browser Use Cloud. It runs AI browser agents on your own Debian, Ubuntu or Raspberry Pi machine, while you choose the model provider, network path, operating budget and access controls. The agent drives a real browser and returns structured data through a documented v3 REST API. The first-party CLI is published on PyPI as openbrowse; the runtime source and releases live in the OpenBrowse GitHub repository.", "Self-hosting is an operational trade-off, not a magic privacy label. You are responsible for securing the host, selecting providers and deciding who may use it. In return, browser profiles, session state and provider credentials stay with the instance you operate instead of being handed to a hosted automation platform. The live dashboard makes each run observable while it works, and the API exposes the status, output and failure information needed to operate it programmatically.", "OpenBrowse at openbrowse.co is maintained by Lucas Johnston Kurilov. It is unrelated to openbrowse.org, openbrowse.ai and the npm package @openbrowse/mcp-server. Names that look alike do not indicate a shared service, maintainer, API or data boundary."] },
      { id: "principles", title: "What the project is for", cards: [{ label: "Ownership", body: "Run the service on hardware and a network you select. There is no OpenBrowse per-task platform charge." }, { label: "Compatibility", body: "Keep the v3 sessions and profiles workflow familiar to existing browser-use-sdk integrations." }, { label: "Evidence", body: "Make agent work inspectable with structured output, a live view and explicit failure states rather than opaque completion claims." }] },
      { id: "start", title: "Read the details", paragraphs: ["Start with the installation guide, review how to expose an instance safely, or inspect the source code on GitHub."] },
    ],
  },
  contact: {
    title: "Contact",
    description: "Where to ask questions, report reproducible problems and inspect the OpenBrowse source code.",
    standfirst: "The project is maintained in public. The clearest route is the one that leaves enough context for someone else to reproduce the problem.",
    sections: [
      { id: "contact", title: "Contact", paragraphs: ["For general project questions, email help@lujstn.com. OpenBrowse is maintained by Lucas Johnston Kurilov, who is also the contact for this website’s information-handling questions. The project source, issue history and release discussion live on GitHub. Before opening a report, check the documentation and search existing issues. If the problem concerns a self-hosted instance, include the version, operating system, the relevant error text and the smallest safe reproduction. Remove API keys, cookies, profile exports and any other credentials before posting."] },
      { id: "routes", title: "Choose the right route", cards: [{ label: "Documentation", body: "Start with setup, authentication and troubleshooting guidance before assuming a behaviour is a defect.", href: "/docs/troubleshooting", linkLabel: "Troubleshooting" }, { label: "Bugs and requests", body: "Use a GitHub issue for a reproducible bug or a well-scoped feature request. Link to the exact release where possible.", href: "https://github.com/lujstn/openbrowse/issues", linkLabel: "Open issues" }, { label: "Source", body: "Read the implementation, releases and licence directly in the public repository. The website repository is separate from the runtime project.", href: "https://github.com/lujstn/openbrowse", linkLabel: "Open source" }] },
      { id: "security", title: "Sensitive reports", paragraphs: ["Do not put a live credential, session cookie, profile storage state or a public exploit path in an issue. Check the repository’s security policy for the current private reporting channel. Until you have a safe channel, share only the minimum redacted information required to establish the impact."] },
    ],
  },
  privacy: {
    title: "Privacy",
    description: "How the OpenBrowse website and the self-hosted OpenBrowse runtime differ when it comes to data and credentials.",
    standfirst: "The public website documents an open-source project. The software itself runs where you install it.",
    sections: [
      { id: "privacy", title: "Privacy", paragraphs: ["OpenBrowse does not provide a hosted browser-agent account or a managed customer workspace. When you install the runtime, its configuration, database and browser profiles live on the machine you operate. Your chosen model provider receives the prompts and browser-derived context needed to answer a task, subject to that provider’s own terms and privacy controls. Lucas Johnston Kurilov maintains this public website and is its contact for privacy questions at help@lujstn.com.", "Browser profiles are especially sensitive: they can contain cookies and web-storage data that grant access to third-party accounts. Keep profile exports out of source control, restrict access to the host and API token, and avoid exposing an instance directly to the public internet. The safe exposure guide and profile documentation explain the operational boundaries in more detail."] },
      { id: "website", title: "This website", paragraphs: ["This website is a public, static documentation and marketing site. It does not ask visitors to create an OpenBrowse account or submit browser-agent credentials. If you follow links to GitHub, PyPI, a model provider, or another external service, that service handles your information under its own policy. GitHub issues are public unless the repository provides a private security-reporting route.", "Like most web hosting, delivery may produce technical request records such as IP address, user agent, requested path and time. Do not send secrets through public pages, issue comments or URLs. If you need to operate the runtime for other people, set your own retention, access and incident-handling policies: you are the operator of that instance and its data."] },
      { id: "changes", title: "Changes and questions", paragraphs: ["This page describes the project’s public site and documented self-hosted architecture, not the privacy policy of every deployment. Material changes will be reflected here. For project questions, use the contact routes and never include credentials or unredacted session data."] },
    ],
  },
  developers: {
    title: "Developers",
    description: "Build against OpenBrowse’s documented self-hosted v3 REST API, with bearer authentication, sessions, profiles and structured output.",
    standfirst: "Use the v3 REST API your instance serves to create browser-agent sessions, preserve authenticated profiles and retrieve structured results.",
    sections: [
      { id: "developers", title: "Developers", paragraphs: ["OpenBrowse is self-hosted. Your application calls the address of the instance you operate, authenticates with its API key and receives data directly from that instance. Existing browser-use-sdk v3 clients can move across by setting their base URL and API key. The public documentation is generated from the runtime’s OpenAPI schema, keeping endpoint descriptions tied to the surface the application actually serves. The first-party CLI is published on PyPI as openbrowse.", "There is no managed OpenBrowse browser API at openbrowse.co and there are no webhooks. This project is unrelated to openbrowse.org, openbrowse.ai and the npm package @openbrowse/mcp-server; do not send credentials, browser work or production traffic to a similarly named service."] },
      { id: "surface", title: "The integration surface", cards: [{ label: "Sessions", body: "Create a task, inspect its status, retrieve messages, stop it or remove it after use.", href: "/docs/api", linkLabel: "API reference" }, { label: "Profiles", body: "Persist cookies and browser storage between runs. Treat each profile as an active credential.", href: "/docs/profiles", linkLabel: "Profiles guide" }, { label: "Operations", body: "Read error classes, cost limits and live run state instead of guessing whether a task completed.", href: "/docs/errors", linkLabel: "Error handling" }, { label: "OpenAPI", body: "Read the machine-readable OpenAPI description published by this website.", href: "/openapi.json", linkLabel: "OpenAPI document" }, { label: "Documentation MCP", body: "Give an MCP client read-only access to this website’s documentation and OpenAPI material.", href: "/mcp", linkLabel: "MCP endpoint" }] },
      { id: "start", title: "Start with the documented contract", paragraphs: ["Read authentication before putting an instance behind an application, then use the published OpenAPI description and v3 API reference for request and response details. If you are evaluating an MCP-based workflow, use this site’s documentation-only MCP endpoint and read the MCP note first: the REST API is the runtime integration contract documented by this project."] },
    ],
  },
} as const satisfies Record<string, TrustPage>;
