/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/openbrowse.ts
 * Command: astryx theme build theme/openbrowse.ts
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

/**
 * openbrowse theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { openbrowseTheme } from './openbrowse';
 *   import './openbrowse.css';
 */
export const openbrowseTheme = {
  name: 'openbrowse',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#60a5fa, #60a5fa)",
    "--color-accent-muted": "light-dark(rgba(96, 165, 250, 0.14), rgba(96, 165, 250, 0.14))",
    "--color-on-accent": "light-dark(#0a0a0a, #0a0a0a)",
    "--color-neutral": "light-dark(#888888, #888888)",
    "--color-background-surface": "light-dark(#111111, #111111)",
    "--color-background-body": "light-dark(#0a0a0a, #0a0a0a)",
    "--color-overlay": "light-dark(rgba(0, 0, 0, 0.66), rgba(0, 0, 0, 0.66))",
    "--color-overlay-hover": "light-dark(rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.04))",
    "--color-overlay-pressed": "light-dark(rgba(255, 255, 255, 0.07), rgba(255, 255, 255, 0.07))",
    "--color-background-muted": "light-dark(#1a1a1a, #1a1a1a)",
    "--color-text-primary": "light-dark(#e5e5e5, #e5e5e5)",
    "--color-text-secondary": "light-dark(#888888, #888888)",
    "--color-text-disabled": "light-dark(#666666, #666666)",
    "--color-text-accent": "light-dark(#60a5fa, #60a5fa)",
    "--color-icon-accent": "light-dark(#60a5fa, #60a5fa)",
    "--color-icon-primary": "light-dark(#e5e5e5, #e5e5e5)",
    "--color-icon-secondary": "light-dark(#888888, #888888)",
    "--color-icon-disabled": "light-dark(#666666, #666666)",
    "--color-background-card": "light-dark(#111111, #111111)",
    "--color-background-popover": "light-dark(#1a1a1a, #1a1a1a)",
    "--color-background-inverted": "light-dark(#e5e5e5, #e5e5e5)",
    "--color-border": "light-dark(#222222, #222222)",
    "--color-border-emphasized": "light-dark(#333333, #333333)",
    "--color-skeleton": "light-dark(#1a1a1a, #1a1a1a)",
    "--color-track": "light-dark(#1a1a1a, #1a1a1a)",
    "--color-shadow": "light-dark(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7))",
    "--color-tint-hover": "light-dark(#111111, #111111)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.3125rem",
    "--font-size-5xl": "2.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3846",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "11px",
    "--text-label-weight": "500",
    "--text-label-leading": "1.6",
    "--text-code-size": "12px",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "clamp(2.125rem, 1.45rem + 2.7vw, 3.5rem)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.04",
    "--text-display-2-size": "clamp(1.5rem, 1.24rem + 1.05vw, 2.125rem)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.12",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.4194",
    "--radius-none": "0px",
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--radius-page": "28px",
    "--radius-chat": "28px",
    "--radius-full": "9999px",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "450ms",
    "--duration-slow": "600ms",
    "--duration-slow-max": "800ms",
    "--font-family-body": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif",
    "--font-family-heading": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif",
    "--font-family-code": "\"SF Mono\", \"SFMono-Regular\", Menlo, Consolas, ui-monospace, monospace",
    "--color-success": "light-dark(#34d399, #34d399)",
    "--color-success-muted": "light-dark(rgba(52, 211, 153, 0.14), rgba(52, 211, 153, 0.14))",
    "--color-on-success": "light-dark(#0a0a0a, #0a0a0a)",
    "--color-warning": "light-dark(#f59e0b, #f59e0b)",
    "--color-warning-muted": "light-dark(rgba(245, 158, 11, 0.14), rgba(245, 158, 11, 0.14))",
    "--color-on-warning": "light-dark(#0a0a0a, #0a0a0a)",
    "--color-error": "light-dark(#f87171, #f87171)",
    "--color-error-muted": "light-dark(rgba(248, 113, 113, 0.14), rgba(248, 113, 113, 0.14))",
    "--color-on-error": "light-dark(#0a0a0a, #0a0a0a)",
    "--color-on-dark": "light-dark(#e5e5e5, #e5e5e5)",
    "--color-on-light": "light-dark(#0a0a0a, #0a0a0a)",
    "--color-text-purple": "light-dark(#a78bfa, #a78bfa)",
    "--color-background-purple": "light-dark(rgba(167, 139, 250, 0.13), rgba(167, 139, 250, 0.13))",
    "--color-border-purple": "light-dark(rgba(167, 139, 250, 0.3), rgba(167, 139, 250, 0.3))",
    "--color-text-blue": "light-dark(#60a5fa, #60a5fa)",
    "--color-background-blue": "light-dark(rgba(96, 165, 250, 0.13), rgba(96, 165, 250, 0.13))",
    "--color-border-blue": "light-dark(rgba(96, 165, 250, 0.3), rgba(96, 165, 250, 0.3))",
    "--color-text-teal": "light-dark(#2dd4bf, #2dd4bf)",
    "--color-background-teal": "light-dark(rgba(45, 212, 191, 0.13), rgba(45, 212, 191, 0.13))",
    "--color-border-teal": "light-dark(rgba(45, 212, 191, 0.3), rgba(45, 212, 191, 0.3))",
    "--color-text-pink": "light-dark(#f472b6, #f472b6)",
    "--color-background-pink": "light-dark(rgba(244, 114, 182, 0.13), rgba(244, 114, 182, 0.13))",
    "--color-border-pink": "light-dark(rgba(244, 114, 182, 0.3), rgba(244, 114, 182, 0.3))",
    "--color-text-green": "light-dark(#34d399, #34d399)",
    "--color-background-green": "light-dark(rgba(52, 211, 153, 0.13), rgba(52, 211, 153, 0.13))",
    "--color-border-green": "light-dark(rgba(52, 211, 153, 0.3), rgba(52, 211, 153, 0.3))",
    "--color-text-red": "light-dark(#f87171, #f87171)",
    "--color-background-red": "light-dark(rgba(248, 113, 113, 0.13), rgba(248, 113, 113, 0.13))",
    "--color-border-red": "light-dark(rgba(248, 113, 113, 0.3), rgba(248, 113, 113, 0.3))",
    "--color-text-orange": "light-dark(#f59e0b, #f59e0b)",
    "--color-background-orange": "light-dark(rgba(245, 158, 11, 0.13), rgba(245, 158, 11, 0.13))",
    "--color-border-orange": "light-dark(rgba(245, 158, 11, 0.3), rgba(245, 158, 11, 0.3))",
    "--color-text-gray": "light-dark(#888888, #888888)",
    "--color-background-gray": "light-dark(#1a1a1a, #1a1a1a)",
    "--color-border-gray": "light-dark(#333333, #333333)",
    "--border-width": "1px",
    "--font-weight-medium": "500"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)",
        "letterSpacing": "-0.032em",
        "color": "#ffffff"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)",
        "color": "#ffffff"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)",
        "color": "#ffffff"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "base": {
        "letterSpacing": "-0.024em",
        "textWrap": "balance"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
