/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/openbrowse.ts
 * Command: astryx theme build theme/openbrowse.ts
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const openbrowseTheme: DefinedTheme;
